/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';

export function Avatar(props) {
  const { camera } = useThree();
  const groupRef = useRef();
  useFrame(() => {
    groupRef.current.rotation.y += 0.01;
    camera.lookAt(groupRef.current.position);
  });
  const { nodes, materials } = useGLTF("models/finalman.glb");
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        name="Wolf3D_Outfit_Top_1"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_1.geometry}
        material={materials.Wolf3D_Outfit_Top}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_1.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_1.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_2"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_2.geometry}
        material={materials.Wolf3D_Eye}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_2.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_2.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_3"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_3.geometry}
        material={materials.Wolf3D_Skin}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_3.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_3.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_4"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_4.geometry}
        material={materials.Wolf3D_Teeth}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_4.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_4.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_5"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_5.geometry}
        material={materials.Wolf3D_Body}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_5.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_5.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_6"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_6.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_6.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_6.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_7"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_7.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_7.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_7.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_8"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_8.geometry}
        material={materials.Wolf3D_Hair}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_8.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_8.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Top_9"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top_9.geometry}
        material={materials.Wolf3D_Glasses}
        morphTargetDictionary={nodes.Wolf3D_Outfit_Top_9.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Outfit_Top_9.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("models/finalman.glb");

